### ISSUE TITLE
Add support for automatic version number updates

### ISSUE THREAD

**Issue by Sharpie** [Sharpie/RTikZDevice#10]
There are a lot of places where the tikzDevice version number and datestamp are used in source code, documentation, etc.  Updating these version numbers should be made automagic by good use of `git tag -a` and `git describe`.

**Comment by Sharpie** [comment]
Automatically adding version info is frowned upon by git as it requires modifying files as they are checked in or out- this means that what you check out isn't the same as what you check in which runs against the core principles of a version control system.

Two approaches that will centralize version number updates to a single file:
1. Write a configure script that performs substitutions with the current version. 
2. Make all tikzDevice output and vignettes reference the version number in the DESCRIPTION file.

Number 2 seems like the most sane option.

**Comment by cameronbracken** [comment]
I agree, option 2 is the way to go, `Print_TikZ_Header` already calls back to R to get this information, no reason that the vignette at least cant do this.

That would only leave the README file....

**Comment by Sharpie** [comment]
Yeah, I've decided to make sure that everything references the version number in the `DESCRIPTION` file- the only thing that really needs to change is the vignette.

We could write a script that updates `DESCRIPTION` and `README.md` with the output of `git-describe`.

**Comment by Sharpie** [comment]
Fixed, there is now a script called `updateVersion.sh` that is in the root folder and added to `.Rbuildignore`.  Invoking this script will update the version number in a new file, `inst/GIT_VERSION`, with either a command line argument, if present, or the output of `git describe`.

`getTikzDeviceVersion` in `R/deviceUtils.R` now references `GIT_VERSION`.  The vignette now calls `getTikzDeviceVersion`.

The `DESCRIPTION` and `README.md` files are still hand-updated.  `DESCRIPTION` won't accept `git describe` version numbers and should only be updated for major releases.  The version number in `README.md` is in the changelog which shows the fixes and additions that are accumulating for the next major version.
