### ISSUE TITLE
Check for / create valid path when creating tikzDevice

### ISSUE THREAD

**Issue by mlt** [Sharpie/RTikZDevice#13]
It would be nice if detailed error is presented to end user instead of generic one. I copy/pasted part of my pgfSweave document and forgot that I specified prefix.string option with folder in it. It took me a while to realize that I don't have output folder for tikz result.

Error in tikzDevice::tikz(file = paste(chunkprefix, "tikz", sep = "."),  :
  TikZ device setup was unsuccessful!

**Comment by Sharpie** [comment]
But what of the long proud tradition of cryptic software error messages?

We'll try to make this more descriptive in an upcoming release--- thanks for the suggestion!

**Comment by cameronbracken** [comment]
I put a more informative error message in tikz() that should address this Issue. 

http://github.com/cameronbracken/rtikzdevice/commit/4a975f5b643d6778a37c97932c7577069758ce6a
