### ISSUE TITLE
Metric Calculations return non-zero exit status

### ISSUE THREAD

**Issue by cameronbracken** [Sharpie/RTikZDevice#17]
On some systems, systems calls to latex return warnings of a non-zero exit status since we use `\@@end` to stop the process.  Warnings look like: 

`running command '/usr/texbin/latex -interaction=batchmode -output-directory /var/folders/Qs/Qs80pcjVHlm3bMdyHfy2W++++TI/-Tmp-//RtmpK8pfqt /var/folders/Qs/Qs80pcjVHlm3bMdyHfy2W++++TI/-Tmp-//RtmpK8pfqt/tikzStringWidthCalc.tex 2>/dev/null' had status 1`

**Comment by cameronbracken** [comment]
Should be fixed by:

https://github.com/cameronbracken/rtikzdevice/commit/2240655b742ccbe31fe584e81cc076ac91b7e385

Simply hides all warnings from the system calls, we know what is going on here and so it is safe to hide this information from the user. Possible other problems could arise if legitimate warnings were ever issues. In that case we may want to consider a different means of suppressing console output.

**Comment by Sharpie** [comment]
Sounds good to me-- I was going to do the same thing and hide the warnings.  I think the best solution would be to run TeX through a pipe that gets opened when `tikz()` is called and closed by `dev.off()`.  Then we don't have to launch TeX for **every  one** of a hundred or so calls to gather font metrics.  Also, if TeX died we would know that something bad really did happen.

**Comment by Sharpie** [comment]
Fixed by cameronbracken/rtikzdevice@2240655b742ccbe31fe584e81cc076ac91b7e385 and merged into master.
