### ISSUE TITLE
Retire the "Mother of All R Hacks"

### ISSUE THREAD

**Issue by Sharpie** [Sharpie/RTikZDevice#19]
The hack in question is used by the vignette to beat some flexibility into Sweave.  Recently, the code had to be redone in order to accomodate changes to Sweave in R 2.12.0.

The result has grown even more monstrous as it checks the R SVN revision number in order to determine which version of the hack to apply---eventually the hack will become a maintenance nightmare.

There is hope in that Romain Francois recently [submitted a patch to R-devel](http://r.789695.n4.nabble.com/embed-Sweave-driver-in-Rnw-file-td3086897.html) that will allow Vignettes to load their own custom Sweave drivers---it is not in R-trunk yet but hopefully it will make it.

**Comment by cameronbracken** [comment]
Seconded.

**Comment by Sharpie** [comment]
Tired of waiting for R-core, so some work is progressing in the `maint/remove-rhack` branch.

Things done:
- The hack has been removed. Also, the vignette uses R's standard Sweave.sty where `\begin{Schunk}` and `\end{Schunk}` are being overridden in `tikzDeviceMacros.tex`.
- The style used by the `listings` package has been altered to gobble `\begin{Sinput}`/`\end{Sinput}` and `\begin{Soutput}`/`\end{Soutput}` so they don't appear in the results. Unfortunately, they leave blank lines behind.
- The code is currently not being set inside a `tikzCodeBlock` but rather a stripped-down version which only captures output and then pipes it back to `\lstinputlisting`. This had to be done because the full code block was replacing `\begin{Sinput}` with `{Sinput}` for some reason.

Things to do:
- See if listings can be convinced to avoid writing out blank lines.
- Re-work the tikzCodeBlock.  Perhaps the frame-breaking methodology can be improved---the [mdframed](http://ctan.org/pkg/mdframed) package is a good place to look for inspiration.

Relevant TeX. stackexchange post:

http://tex.stackexchange.com/questions/16299/search-and-replace-in-a-token-list

**Comment by Sharpie** [comment]
This is mostly complete. Lots of convoluted TeX hacking occured in Sharpie/RTikZDevice@17ddc908b4900a50758050590560b4c2ec43f016 that sets up the `Schunk` environment so that it strips out the `Sinput` and `Soutput` environments without leaving behind blank spaces.

Work left to do is to re-wrap this into a tikzCodeBlock.
