### ISSUE TITLE
Compilation Warnings 

### ISSUE THREAD

**Issue by cameronbracken** [Sharpie/RTikZDevice#2]
tikzDevice.c:1425: warning: initialization discards qualifiers from pointer target type

This is due to mismatches of `char *` with `const char *`.  Need to fix before v0.5 on CRAN.

**Comment by Sharpie** [comment]
C programmer says WHAT?

**Comment by cameronbracken** [comment]
I say why do I have to think about this?

**Comment by cameronbracken** [comment]
Fixed by creating a copy of the string with the qualifier mismatch and returning that. Ugly hack but it works. 

Who's a C programmer now!
