### ISSUE TITLE
Output plots to separate files

### ISSUE THREAD

**Issue by cameronbracken** [Sharpie/RTikZDevice#29]
Similar to the `onefile` option to the `pdf()` device. 

This could be useful for micro-managing how plots are arranged in a tex document yet still generating them in a loop.  May be especially useful when using Sweave.

**Comment by cameronbracken** [comment]
Bam! [d0479af6](https://github.com/cameronbracken/rtikzdevice/commit/d0479af6f25e09994992cbb83564a233fee54621)

**Comment by Sharpie** [comment]
@cameronbracken If this code is ready, open a pull request and we can merge it into the master branch!

I'll probably be rolling up another R-Forge release when the [Grid Annotation](https://github.com/Sharpie/RTikZDevice/issues/37) code is finished.
