### ISSUE TITLE
Stack mismatch warning when printing header

### ISSUE THREAD

**Issue by cameronbracken** [Sharpie/RTikZDevice#3]
In commit [00b8efb5f3a](http://github.com/cameronbracken/rtikzdevice/commit/00b8efb5f3a98e5e3bbe21c9cb9e24c390794316)

```
> tikz()
Warning: stack imbalance in '.External', 8 then 9
Warning: stack imbalance in '{', 6 then 7
```

Likely something in `Print_Tikz_Header`

**Comment by Sharpie** [comment]
This usually means more C variables were PROTECTed than UNPROTECTED.  Check the version number and time stamp callbacks in TikzHeader.

**Comment by cameronbracken** [comment]
Fixed! Thanks Charlie!
