### ISSUE TITLE
Fix Vignette issue

### ISSUE THREAD

**Issue by Sharpie** [Sharpie/RTikZDevice#32]
Appears there is some issue preventing the vignette from building. This is blocking binary builds on CRAN although it is being flagged as a NOTE rather than a ERROR. Just ran into it for the first time when prepping the `r-forge` branch for a release. [Gist of  log here](https://gist.github.com/920011).

Coincidentally, Murphy's law is goddamn **spooky**. I ran this operation for three different versions of R on 3 different platforms and the bug doesn't show up until **AFTER** the CRAN release? WTF!?!

**Comment by cameronbracken** [comment]
gah, figures

**Comment by Sharpie** [comment]
It looks like `git` outsmarted it's self when I merged the master branch to the R-Forge branch for the release. Some stuff in the Sweave patch got duplicated that wrecked the R-2.13.0 build.

I can't wait to get rid of that thing, it is becoming a maintenance nightmare.

**Comment by Sharpie** [comment]
Fixed in CRAN release 0.6.1
