### ISSUE TITLE
UTF8 Support for LaTeX

### ISSUE THREAD

**Issue by Sharpie** [Sharpie/RTikZDevice#4]
Figure out how to do UTF8 support using `pdftex` in a sane way. `pdftex` is the garden variety of TeX that everyone has and uses to power `latex` and `pdflatex`.

**Comment by Sharpie** [comment]
This is very, very, very, very hairy.

The quickest way may be to polish support for next-gen typesetting engines such as XeTeX and LuaTeX.

**Comment by cameronbracken** [comment]
First viable attempt at UTF-8 support:

http://github.com/cameronbracken/rtikzdevice/commit/82fecacbbda2d57d1d14dfc90ff692220c22eb72

Uses XeLaTeX to calculate metrics of multibyte (unicode) characters.  I'm sure there are going to be a whole pile of issues related to encoding and locales and all that voodoo that I don't really understand.

**Comment by Sharpie** [comment]
Thanks to Cameron's hard work, we now have UTF-8 support via `xetex`!  Hopefully `luatex` can be added in the next major release.

`pdftex` is a mess---for now we will leave it up to the user to load the correct concoction of packages required to typeset their Unicode. This is probably the way things will stay.
