### ISSUE TITLE
more tikzSanitizeCharacters

### ISSUE THREAD

**Issue by yihui** [Sharpie/RTikZDevice#63]
`>` to `\textgreater{}` and `<` to `\textless{}`

see http://stackoverflow.com/q/12672835/559676

**Comment by krlmlr** [comment]
Doesn't occur if `fontenc` is loaded with `T1` option in LaTeX: http://tex.stackexchange.com/a/2376/8057. Also perhaps fixed by https://github.com/aussetg/RTikZDevice/commit/010783f906dae0651c83111fc98a586461342506 .

**Comment by yihui** [comment]
That is right. T1 is the solution. I realized it later, so this issue can be closed now.
